[workspace]
resolver = "3"
members = [
    "crates/pethit-node",
    "crates/pethit-storage",
    "crates/pethit-execution",
    "crates/pethit-rpc",
    "crates/pethit-txpool", 
    "crates/pethit-consensus",
]

[workspace.dependencies]
alloy-primitives = { version = "1.5.0" }