[package]
name = "pethit-txpool"
version = "0.3.0"
edition = "2024"

[dependencies]
pethit-execution ={ path = "../pethit-execution" }
alloy-primitives = { workspace = true }

[dev-dependencies]
k256 = { workspace = true }
