[package]
name = "pethit-consensus"
version = "0.2.0"
edition = "2024"

[dependencies]
pethit-execution = { path = "../pethit-execution" }
pethit-storage = { path = "../pethit-storage" }
pethit-txpool = { path = "../pethit-txpool" }

alloy-primitives = { workspace = true }
