[package]
name = "pethit-execution"
version = "0.3.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }
k256 = { workspace = true }
pethit-storage = { path = "../pethit-storage" }
